name: stefanovirgilli
favicon: null
layout_spectrum: 0.7233661497011781
typography_spectrum: 0.3549248571507633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3964003233704716
  lightness: 0.060239871265366673
  saturation: 0.9917833120562136
  rhythmicContrast: 0.7290617539547384
purpose: []
